stages:
  - test
  - build

test:
  image: mcr.azk8s.cn/dotnet/core/sdk:3.1
  stage: test
  script:
    - dotnet test web-backend.sln
    
build:
  image: mcr.azk8s.cn/dotnet/core/sdk:3.
  stage: build
  before_script:
    - dotnet restore
  script:
    - dotnet publish -c release