stages:
  - test
  - build

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2 
  DOCKER_TLS_CERTDIR: ''

test:
  image: registry.cn-hangzhou.aliyuncs.com/shinetechchina/dotnet_core_sdk:3.1
  stage: test
  script:
    - dotnet test web-backend.sln
    
build:
  image: docker:stable
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login --username=${REGISTER_NAME} registry.cn-hangzhou.aliyuncs.com --password ${REGISTER_PASSWORD}
  stage: build
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .
    - docker service update --image "${CI_PROJECT_PATH}:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA" web-backend