stages:
  - test
  - build

test:
  image: registry.cn-hangzhou.aliyuncs.com/shinetechchina/dotnet_core_sdk:3.1
  stage: test
  script:
    - dotnet test web-backend.sln
    
build:
  image: docker:stable
  services:
     - docker:dind
  
  before_script:
    - docker login --username=${REGISTER_NAME} registry.cn-hangzhou.aliyuncs.com --password ${REGISTER_PASSWORD}
  only:
    - master
  stage: build
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest